### ISSUE TITLE
Page title bar height in View Answer page

### ISSUE THREAD

**Issue by nitinpaul** [sawaliram/sawaliram#123]
The title bar for the View Answer page has a height issue. The text is there, it's white against white therefore not visible, but the page title bar loses it's height.

**Comment by PeterMorganGH** [comment]
`.answer-section` has a negative top margin set with `margin-top: -5rem;`. Remove that and the title bar will display like the other pages. You may also want to remove `padding-top: 5rem;` from `.answer-section`.
