### ISSUE TITLE
No logs are generated/stored 

### ISSUE THREAD

**Issue by nitinpaul** [sawaliram/sawaliram#13]
Add or enable a robust logging system for the project. Logs are a critical component of any hosted platform and we cannot go into production without some form of logging enabled. Before setting up a logging system, please discuss the options.

**Comment by badrihippo** [comment]
What kind of storage do we use for the log? I've setup a basic file-based logging (`sawaliram.log`) to start with, but we should probably choose a more scalable option. Some other possibilities are:

* **RotatingFileHandler**—basically, it creates a  file after exceeding a specific length (`sawaliram.log.1`, `sawaliram.log.2`, etc.). There's also a variation called **TimedRotatingFileHandler** that automatically pushes over after a specified time.
* **SysLogHandler** that saves logged data to the system log (/var/log or whatever)
* **SMTPHandler** which reports errors by email

We can also use different ones or combinations depending on the context—which brings up the second question: what all events are we planning to log?

Logs can have a level of INFO, DEBUG, WARNING, ERROR, or CRITICAL; here's a list of some events I can think off right now.

* [info] User creates account
* [info] User logs in?
* [info] User submits question
* [info] User submits excel-sheet
* [warning] 404 error is triggered

There will of course be more events as we build out the website features; in that case we could look at splitting logs so different kinds of event get logged in different places. (Django has an in-built system for this kind of fine-grained filtering, based on python's `logging` module).

[This blog post](https://lincolnloop.com/blog/django-logging-right-way/) mentions using the same system for Sentry, by simply adding it as a handler. So this could eventually be useful for #16 as well.

**Comment by nitinpaul** [comment]
This looks like a good starting point. I can see the benefits of being able to do something like ```logger.info("The value of var is %s", var)```. 
+1 for Sentry. Having used it for over a year, I can vouch for its usefulness. I would say we will most definitely use Sentry, but since it involves payment (for the service), I will discuss the finance part of it and update this thread.

**Comment by badrihippo** [comment]
Pull #26 implement basic logging. I haven't added Sentry since there are no "critical errors" to report as of now, but (as I mentioned in Slack) we can easily create a "dummy Sentry" logfile and then switch over to the actual Sentry if/when it gets set up.

**Comment by badrihippo** [comment]
Close this too, since Sentry is implemented and the linked PR is closed?
