### ISSUE TITLE
The comment should be generalised for all content

### ISSUE THREAD

**Issue by nitinpaul** [sawaliram/sawaliram#151]
Instead of having different models like `AnswerComment` and `ArticleComment`, there should be general model for all comments that can be linked to any content model.

**Comment by badrihippo** [comment]
@nitinpaul I can start on this and #150. Is it okay if I merge it into the Translations branch at some point so I can use its functionality for the Review Translation pages? I can send it for you to review first and then merge it in here instead of you sending it to the trunk.

**Comment by nitinpaul** [comment]
Go for it @badrihippo
Eager to see the implementation!

**Comment by badrihippo** [comment]
@nitinpaul is it fine if all existing comments get deleted? That'll be simpler since we won't have to worry about migrations etc.
