### ISSUE TITLE
"Review Answer" page crashes on reload

### ISSUE THREAD

**Issue by badrihippo** [sawaliram/sawaliram#176]
The Review Answers page works only when it's loaded from another page. If you try to load it directly (eg. by typing in the URL manually or hitting reload), it throws the error:

    argument of type 'NoneType' is not iterable

It seems it's trying to do something with `HTTP_REFERER` but not able to when `HTTP_REFERER` does not exist (as happens when the page is loaded directly).

@nitinpaul why are we trying to save the Review Answers URL in the review session anyway?

**Comment by nitinpaul** [comment]
To set up the Next/Prev links
