### ISSUE TITLE
Search feature: 'Articles' included in question search 

### ISSUE THREAD

**Issue by dchandrika-tifr** [sawaliram/sawaliram#204]
"Yesterday (20 Feb) Nitin did some significant re-writing of the search function. Before he did it (since 19 Feb) the search bar did not work at all. After he did it the article is showing up in the search even when it is unselected in the filter" (refer to email from JR on 21/02/2020 at 16:22hrs. 

Badri - " here seems to be a slight logic issue in the search page; it only applies result type filters if something is typed into the search bar (otherwise returns everything by default). I'll ask Tannu to look into this since she's working on the search page right now."

**Comment by jr-sawaliram** [comment]
@nitinpaul, @badrihippo, for when is this fix scheduled?

**Comment by jr-sawaliram** [comment]
The article looks very odd on the search page. I am holding on till the fix to ask Debashree to edit the next one.

**Comment by badrihippo** [comment]
Already fixed in #213. It just needs to be merged in and deployed to the live site.

**Comment by jr-sawaliram** [comment]
Thanks, Badri!

**Comment by badrihippo** [comment]
The fix is by @tannucheria. She was also going to make pagination (showing only 15 results per page) apply to articles etc., but that probably won't happen now so we can just merge this in and fix the pagination separately later.

**Comment by jr-sawaliram** [comment]
@nitinpaul, @badrihippo, what is the latest on this issue?
