### ISSUE TITLE
JR profile page: Shows 'Review pending' for a published answer 

### ISSUE THREAD

**Issue by dchandrika-tifr** [sawaliram/sawaliram#205]
There seems to be a bug/logic error as a answer submitted by an expert that has been published shows up as "Review Pending" in JR's profile.

**Comment by jr-sawaliram** [comment]
It's not just me. Anish reported the exact same problem in his profile.

**Comment by badrihippo** [comment]
This seems to be a data problem. @nitinpaul can you check the value of `[answer].status` and send it to me?

@jr-sawaliram is this happening for all answers or just this particular one? When other people submit answers do they show up properly as "published"?

**Comment by badrihippo** [comment]
> This seems to be a data problem. @nitinpaul can you check the value of [answer].status and send it to me?

@dchandrika-tifr or you can do this: open up the answer via Admin and tell me what `status` is set to (is it `0`, `1`, `submitted`, `published`, or something else altogether?)

**Comment by jr-sawaliram** [comment]
> @jr-sawaliram is this happening for all answers or just this particular one? When other people submit answers do they show up properly as "published"?

I have only one answer. It's happening to all of Anish's answers. Nitin said it will be fixed when he pushes the user profile.

**Comment by dchandrika-tifr** [comment]
The status for the 17 answers in the system is either  published/ draft/
submitted.
1- draft; 3- submitted;  13 published

**Comment by badrihippo** [comment]
Oh okay :+1:

**Comment by badrihippo** [comment]
Okay. Seems to be using the old format for tracking drafts; I'll leave it to @nitinpaul to sort it out and check in later if there are still issues :stuck_out_tongue:
