### ISSUE TITLE
Profile page shows editable content when displaying another user's profile

### ISSUE THREAD

**Issue by badrihippo** [sawaliram/sawaliram#221]
When a user (let's call them Hugin) views the profile of another user (henceforth referred to as Munin), it shows details like drafts, bookmarks, etc of Munin but the "Settings" page is that of Hugin.

What's more, the buttons for drafts, etc. are clickable, meaning Hugin can potentially open the "edit" page for Munin's articles. This does not actually happen, because the respective views prevent a user from editing anothers' articles: clicking "Edit" on an answer, for example, would open a new answer for the selected question rather than changing Munin's in-progress draft. Articles, on the other hand, seem to actually allow one user (Hugin) to edit another's  (Munin's) article.

Bookmarks are of course read-only, but would it be considered a privacy violation if one user was able to view anothers' bookmarks?

Tagging @dchandrika-tifr who was also present when this bug was discovered.

**Comment by nitinpaul** [comment]
Working on this currently
