### ISSUE TITLE
Multiple answers: Message with prompt, button placement and randomization

### ISSUE THREAD

**Issue by dchandrika-tifr** [sawaliram/sawaliram#250]
Allow "Re-answering question" button after the answer is viewed with a different prompt? 

"Do you know any other way to answer this question or would like to add additional information?" **Submit another answer**

JR's suggestion (on Zulip): "I suggest, after any question is answered for a second time, the next suggestion for a question to answer should be the next unanswered question."

**Comment by jr-sawaliram** [comment]
So why call it 'randomization'?
