### ISSUE TITLE
Search filter text must fit in the buttons

### ISSUE THREAD

**Issue by jr-sawaliram** [sawaliram/sawaliram#255]
Text of the State filter 'Andaman & Nicobar' spills out of the button. Text of 'History, Philosophy & Practice of Science' is not quite centered as yet.

**Comment by dchandrika-tifr** [comment]
This has been taken up by Badri 12 days ago. 

Currently, there are 4 filters that need text wrapping. 
-Subjects: History, Philosophy and Practice of Science
-States: Madhya Pradesh, Andhra Pradesh, Andaman & Nicobar

**Comment by badrihippo** [comment]
Fixed by #324
