### ISSUE TITLE
No custom error 500 page

### ISSUE THREAD

**Issue by nitinpaultifr** [sawaliram/sawaliram#3]
Currently, the system displays a generic string response for error 500 which does not provide the user with any information on possible next steps and does not have a call to action to either go back to the previous page, go to the home page or simply reload the page. We need a custom error_500 handler similar to the error_404 handler.

**Comment by jr-sawaliram** [comment]
Partly fixed by #396. More features as above are to be added.

**Comment by badrihippo** [comment]
@jr-sawaliram can you elaborate on what features are to be added, exactly?

**Comment by jr-sawaliram** [comment]
We were thinking to design custom error pages for sawaliram but I vote for now we do without. We could reopen the issue if and when a graphic designer creates such pages.
