### ISSUE TITLE
Language selector flips after submission of translation

### ISSUE THREAD

**Issue by jr-sawaliram** [sawaliram/sawaliram#360]
Set CONTENT_LANGUAGES as available languages in answer and article translations.
Available languages are those in which questions have been submitted so far.

Symptom of the issue is that the language selector flips after submission of translation. For answer translation:
After submission Marathi-->English answer translation gets labelled Marathi-->Bangla

For  article translation:
After publication English-->Bangla article translation gets labelled English-->English. Hence it is not viewable on the site.

**Comment by abhiprojectz** [comment]
Can anyone please check once as far as ,the language in answers translation after submission is not flipping.

while,
` For article translation:
After publication English-->Bangla article translation gets labelled English-->English. Hence it is not viewable on the site. `
is a issue its flips.
