### ISSUE TITLE
Translator cannot edit submitted translation after review

### ISSUE THREAD

**Issue by jr-sawaliram** [sawaliram/sawaliram#361]
Submitted translation or answer or article should be editable after a review.

**Comment by badrihippo** [comment]
It looks like the page is coming but the content is not editable. Possibly some issue with activating the editor?

**Comment by abhiprojectz** [comment]
@badrihippo  Actually its problem with the reviewing view not with activating the editor as the page for activating the editor suppose to be on a different endpoint that it something like `translate/answers/<int:pk>/<int:answer>/edit` 

but as their is error with translation model/logic the **actual (editable)** url of `Edit Translation` button  is not passing like in [this template](https://github.com/sawaliram/sawaliram/blob/dd90a9b0c08d3d3c0f7320b0245f6f58563011bc/dashboard/templates/dashboard/translations/answer_review.html#L78) 

In result the `Edit Translation` button url is same as the review page for answers translation editing.

**Comment by abhiprojectz** [comment]
Also i have doubt in [AnswersTranslation model](https://github.com/sawaliram/sawaliram/blob/dd90a9b0c08d3d3c0f7320b0245f6f58563011bc/dashboard/models.py#L284)  utility `def get_edit_url(self)` is not created (or missing ?) for **answer translation** while for articles it exists. 

It seems maybe its the reason for disabling of `editing` [as in line for answers](https://github.com/sawaliram/sawaliram/blob/dd90a9b0c08d3d3c0f7320b0245f6f58563011bc/dashboard/templates/dashboard/translations/base_review.html#L46)

**Comment by badrihippo** [comment]
@abhiprojectz I think the `get_edit_url` function is present in the question model instead of the answer one, for question/answer translations. Can you check if that is the case?

Alternatively maybe you need to define the function now. The URL for editing draft translations is different from the URL for editing submitted ones; take a look at the Edit Answer Translation view for an example. (You will also see both entries in `dashboard/urls.py`).

**Comment by abhiprojectz** [comment]
I searched the [dashboard/views.py](https://github.com/sawaliram/sawaliram/blob/dd90a9b0c08d3d3c0f7320b0245f6f58563011bc/dashboard/models.py) only one function is present and that is for `articles`. 

Anyways , i have created that function and resolved some bugs in the `review` view , will soon make the PR.
