### ISSUE TITLE
Login icon on home page to change

### ISSUE THREAD

**Issue by jr-sawaliram** [sawaliram/sawaliram#387]
<img width="192" alt="Screenshot 2021-06-01 at 11 19 28 AM" src="https://user-images.githubusercontent.com/46344161/120273558-4adc4a80-c2cc-11eb-8323-1f7fb0be2ee6.png">
Please up/down vote on this suggestion.

**Comment by abhiprojectz** [comment]
@jr-sawaliram  what about this ?

![22333](https://user-images.githubusercontent.com/64596494/120796090-01a02b00-c558-11eb-8dec-1e307a49a56e.PNG)
