### ISSUE TITLE
Attaching images in the editor saves it as base 64 encoded string instead of an img tag with path to the image

### ISSUE THREAD

**Issue by nitinpaul** [sawaliram/sawaliram#41]
Ideally the html from the editor with an attached image should be saved as an <img> with the attached image stored as a static resource on the server somewhere. Check if quill.js somehow supports this out of the box. Or, the alternatives are:
1. Increase the size of the answer_text to fit the huge string
2. Manually convert the string to jpeg on the server-side, store it and modify the html string with the new path to the image.

I am looking into the pros and cons involved, will update the issue.

**Comment by badrihippo** [comment]
Check out [this comment](https://github.com/quilljs/quill/issues/863#issuecomment-318259515) for uploading an image by AJAX and then embedding to the QuillJS editor. I haven't tested it, but seems worth a look.

Meanwhile, Django has an `ImageField` type, with an `upload_to` option. We could create a new `ImageField` for each image linked to the answer; that'll also help us keep track of which images are for which answers (and delete them easily if/when the time comes).

We could also use [Plupload](https://www.plupload.com/) in a popup (though that *might* be an overkill).

**Comment by nitinpaul** [comment]
The images could be saved as base 64 strings, but we want one picture for every blog and answer for the thumbnail, and of course one cover picture for the blog. How about this - once the user has done typing in the answer, we can detect the images using JS and show the user a popup to select one image for the thumbnail (which fits our required dimensions). For blogs of course, there will be field in the form to upload a cover picture.

**Comment by badrihippo** [comment]
Makes sense. We could also default to using the first image, and let the user change it if they want to.

But how do we implement it on the server side? A separate model for each picture, or just inline base64? If the former, it'll make more sense to use an `ImageField` and save an actual image file rather than `base64`, the only caveat being we'd need a clause (or script) to automatically remove orphaned images. This will also help people edit answers quicker, without having to "upload" the images again each time.

**Comment by nitinpaul** [comment]
We might not need a model for the images - we will save the entire answer as it is - base 64 strings for the images are fine, it might even make fetching an answer or a blog post faster since all the content - text and images - is retrieved in a single request. What we can do is when a user clicks submit, we can detect the images attached to the editor, convert the base64 strings to images, show the ones that have the right dimensions, and let the user select a thumbnail image. When they do, we save the image separately as a static resource. The answer or the blog model will need to have a field for storing the name or path to this image.

**Comment by badrihippo** [comment]
There are three reasonably active projects, all of which offer WYSIWYG editors with built-in upload-to-Django support.

* [django-ckeditor](https://github.com/django-ckeditor/django-ckeditor) for CKEditor integration
* [django-tinymce4-lite](https://github.com/romanvm/django-tinymce4-lite) using TinyMCE 4
* [django-summernote](https://github.com/summernote/django-summernote) powered by the Bootstrap-compatible Summernote editor

All these projects upload images separately and insert the appropriate `<img .../>` tags; we just have to specify a `media` folder. They also provide a custom form field (eg. `HTMLField`) to handle the rendering.

Might be worth a look? This will also help a lot if we're going to do anything about #145 right now.
