### ISSUE TITLE
Translations not appearing in 'Manage Content'

### ISSUE THREAD

**Issue by jr-sawaliram** [sawaliram/sawaliram#417]
After merging PR #407 the article & answer translations are not appearing at the manage content interface. However they are counted in the count shown on the top of the page.

**Comment by ukey54** [comment]
For me 
article & answer translations are appearing at the manage content interface.

**Comment by jr-sawaliram** [comment]
@ukey54, they appear fine locally but not on the Sawaliram site. @nitinpaultifr @badrihippo could it be an issue with migrations? I have posted the server output on Zulip.

**Comment by jr-sawaliram** [comment]
Good news! Now translations appear at 'Manage Content'. It may have happened after merging of #406 or #402 yesterday or #416 two days ago. Would be good if someone could tell.
