### ISSUE TITLE
Submit review gives Error 500

### ISSUE THREAD

**Issue by jr-sawaliram** [sawaliram/sawaliram#418]
Submitting the review of an answer gives Error 500 internal server error. The review comment is seen in the submitter's 'Submissions' immediately. Notification is received after a while.

**Comment by ukey54** [comment]
Same goes for me too.
<img width="1280" alt="PR418" src="https://user-images.githubusercontent.com/11020198/123294269-53721a80-d532-11eb-9afe-861ae3724617.png">

**Comment by abhiprojectz** [comment]
it seems there is a small error in codebase
