### ISSUE TITLE
Article 78 gives Error 500

### ISSUE THREAD

**Issue by jr-sawaliram** [sawaliram/sawaliram#419]
https://sawaliram.org/article/78/ This link gives an internal server error. The other articles are visible.

**Comment by abhiprojectz** [comment]
It works fine locally so, It seems article routing is not taking place on the server correctly.
Two things can be done:

1. Change the article's title to something like `seedhe sawal tedhe jabab`  or
2. Unpublish (or maybe delete) the article and then, create a new article with the same data as per `article 78` (from admin panel).

**Comment by jr-sawaliram** [comment]
As discussed with @badrihippo 'Make slug function multilingual'
