### ISSUE TITLE
Fix "Student class" value that represented as 'float' to 'integer' 

### ISSUE THREAD

**Issue by dchandrika-tifr** [sawaliram/sawaliram#434]
While displaying metadata of questions, the value of "Student Class" is represented as a float value than an integer. See image. 
The class field should be integer value. 

![image](https://user-images.githubusercontent.com/46741301/126155664-6035c41d-90cb-4097-b865-1c1f4d120655.png)

**Comment by abhiprojectz** [comment]
@dchandrika-tifr  can you please share the links to these question , as in local database dump , this is not showing up.
