### ISSUE TITLE
'Write an Article' view is missing

### ISSUE THREAD

**Issue by nitinpaul** [sawaliram/sawaliram#59]
The designs are titled 'Blog' in the final design folder, which can be found in the #design channel of our Zulip server. Check out the [documentation for quill.js](https://quilljs.com/docs/quickstart/) to find out how to configure it. This page will require minimal work, and would be a good issue to get started with the back-end code!

**Comment by badrihippo** [comment]
Fixed by #129. @nitinpaul please close.
