### ISSUE TITLE
Task statistics on the dashboard home is static

### ISSUE THREAD

**Issue by nitinpaultifr** [sawaliram/sawaliram#6]
Information about the work completed/pending for any task is displayed on the home page. Currently this value is static (for design). Ideally, these values should be updated once or twice a day and should be fetched from a service like memcached to reduce load on the database. We will also need to set up a cron job to run the script periodically to update these values. A rough checklist of things to do:
- Write a script to calculate the values and update memcached (or similar service)
- Set up a cron job to execute the script at fixed intervals
- Update the views.py to read the values from memcached (or similar service)

**Comment by badrihippo** [comment]
@hitarths can you check if this task is complete? If so, we should close this issue.

**Comment by hitarths** [comment]
Seems fine.
