### ISSUE TITLE
User profile view missing

### ISSUE THREAD

**Issue by nitinpaul** [sawaliram/sawaliram#7]
On clicking the user profile button on the navbar, users should see a profile page where a user may:

- Change/Reset password
- View all submitted content (with seperate sections for)
- Change preferences for email notifications

Create a basic design for the user profile (after discussions) to close this issue.

**Comment by Raul9595** [comment]
Can I work on this ?

**Comment by nitinpaul** [comment]
Hey Rahul, sure! We're going to have to wait a bit (Friday this week) for our design team to send us the designs for this page, but once they do, we can get started!
