### ISSUE TITLE
Setting up mail system

### ISSUE THREAD

**Issue by nitinpaul** [sawaliram/sawaliram#8]
Set up an email service for sending transactional emails (signup, password reset, email notifications etc). MailGun is a good candidate. Any good candidate would have a good API and documentation. Keep in mind that this service will be used site-wide and will need to be scalable.

To close this issue, add the configurations for an email system.

**Comment by badrihippo** [comment]
Might be worth checking out the Anymail plugin for Django: https://github.com/anymail/django-anymail

**Comment by badrihippo** [comment]
@nitinpaul shall I start work on this? Are we doing anymail as a dependency, anymail as a copy-paste, or hand-writing custom code?
