### ISSUE TITLE
Button CSS has inconsistent styling

### ISSUE THREAD

**Issue by badrihippo** [sawaliram/sawaliram#90]
The primary button style is inconsistent with the styling of the other buttons, making it problematic to quickly change the style of a button.

In `style.css`, the `.btn-primary` class specifies `display: inline-block`, whereas the other `.btn-*` classes have no `display` property set. This means that changing the class from primary to (say) secondary, in addition to updating the colours, could also unexpectedly change the way the button is displayed.

We should either move the `display: inline-block` to a separate class (if it needs to be used for primary buttons only in some places) or add it to the styling for `.btn` (if it is to be applied for all buttons).

**Comment by nitinpaul** [comment]
Good find! I think we should move it to `.btn`
